### PR TITLE
Icon all

### PR DESCRIPTION
**Pull request by roblevintennis**
- Type of work: other
- Deployment URL: https://mavenlink.github.io/design-system/icon-all
- (Optional for outside contributions) Tracked work in Mavenlink: https://www.pivotaltracker.com/story/show/167436613

## Motivation

List of SVGs Follow Up
[x] MDS site has a list of SVGs.

image

## Acceptance Criteria
* MDS site has a list of SVGs

### CODE REVIEW

**Comment by juanca** [comment]
Closes https://github.com/mavenlink/design-system/issues/25

**Comment by roblevintennis** [comment]
What do you mean this closes #25? You mean when merged? You didn't approve it so I'm a bit confused.

**Comment by juanca** [comment]
Right. Sorry. It's Github-fu. Making that comment will automatically link this PR with the issue. In addition, since I am tracking the issue in a Github Project, it will also automate the status of the issue: dev => dev done => reviewable => merged, type of deal.

**Comment by roblevintennis** [comment]
gotcha

**Comment by roblevintennis** [comment]
Here's the staged version:

image

**Pull request merged**
