### PR TITLE
converts px vars to rems

### PR DESCRIPTION
**Pull request by BenHSmith13**
Co-authored-by: Taylor Dunn <tdunn@mavenlink.com>
Co-authored-by: Juan-Carlos Medina <juanca@mavenlink.com>

## Motivation
[EM vs REM vs PX – Why you shouldn't “just use pixels”](https://engageinteractive.co.uk/blog/em-vs-rem-vs-px)

TL:DR: Pixels aren't accessible

## Acceptance Criteria
- By default everything should look the same
- Open chrome://settings/appearance (or your browsers settings
- Change the default font size
- [ ] Components that consume these font variables should now reflect your browsers font.

This is a screenshot with browser font size set to normal

Screen Shot 2021-10-21 at 9 57 41 AM

This is the same screen with the browser font size set to Extra Large

Screen Shot 2021-10-21 at 9 57 57 AM

## PR upkeep checklist

- [X] Change log entry
- [X] Label(s)
- [X] Assignee(s)
- [X] Deployment URL: https://mavenlink.github.io/design-system/rems-4-life/
- [X] (When ready for review) Reviewer(s)
- [x] Green Bigmaven CI check https://github.com/mavenlink/mavenlink/pull/27023
- [x] DevQA on Bigmaven staging (e.g. does the work need to be imported in the internal design system?)

### CODE REVIEW

**Review by juanca — DISMISSED** [review]
To avoid accidentally merging this. We need to talk to design first. Possibly convert all pixel values to REM in this repo.

**Comment by BenHSmith13** [comment]
> To avoid accidentally merging this. We need to talk to design first. Possibly convert all pixel values to REM in this repo.

Do we need to make a go-forward plan for this?

**Comment by juanca** [comment]
Oh. yeah, I had lost this in the PR noise + OOO. I know we met up with design. But I forgot about any action items. 

1. Do we have remaining px values to convert to rem values?
2. What other actions items were raised during our meeting?

I can see that we want to bake these changes on "all user-facing" staging server for a few weeks. I can do that (I have a script and all) if this is ready to be staged.

**Comment by BenHSmith13** [comment]
There are a bunch of px values tucked into individual css files. Most seem like one-off values. I am happy to go change them to rems.

I think the only item from Pendulum meeting was "wait till product reviews are over." I believe those are done.

**Comment by juanca** [comment]
> There are a bunch of px values tucked into individual css files. Most seem like one-off values. I am happy to go change them to rems.
> 
> I think the only item from Pendulum meeting was "wait till product reviews are over." I believe those are done.

Yeah, I'm not sure how much value we would get from remifying the one-offs. If we think it's better to be consistent for rems then let's do it. Otherwise, I can stage this later this week.

**Comment by juanca** [comment]
@BenHSmith13 Do you already have a bigmaven branch/PR for using this MDS branch? Otherwise, I can make one.

**Comment by BenHSmith13** [comment]
I do not

**Comment by juanca** [comment]
I will be merging + releasing end of week. Looks like there has been 0 feedback on any regressions.

**Pull request merged**
