### PR TITLE
Fix issue where validation hook was not re-rendering on changes and w…

### PR DESCRIPTION
**Pull request by bennapp**
## Motivation
Fix issue where required fields were in an errorState with a value on first render.
https://www.pivotaltracker.com/story/show/175152537

## PR upkeep checklist

- [x] Change log entry
- [x] Label(s)
- [x] Assignee(s)
- [x] Deployment URL: https://mavenlink.github.io/design-system/webinf-validation-issues-175152537/
- [x] (When ready for review) Reviewer(s)
- [x] Green Bigmaven CI check
  - Usage in Custom Form's config page: https://github.com/mavenlink/mavenlink/pull/21853
- [x] DevQA on Bigmaven staging (e.g. does the work need to be imported in the internal design system?)

### CODE REVIEW

**Review by cincospenguinos — APPROVED** [review]
LGTM!

**Comment by juanca** [comment]
@bennapp I deployed the PR to webinf_rc as part of https://github.com/mavenlink/mavenlink/pull/21853

It looks good on the bigmaven design system site and it is green with a minor test update.

**Comment by juanca** [comment]
@bennapp Did you have a bigmaven use-case? Is there a PR for that?

**Comment by bennapp** [comment]
Awesome!! That PR is already in master @juanca it was where we were introducing the form's title.

**Comment by juanca** [comment]
I am merging and making a release.

**Pull request merged**
